### ISSUE TITLE
Handling of name clashes for endpoints

### ISSUE THREAD

**Issue by jaw111** [CLARIAH/grlc#344]
Opening this to continue discussion from #331 about handling of name clashes for endpoints that may arise if the 'local' names of sparql queries are the same. Let's say I reference queries `http://example.com/path/query.rq` and `http://example.com/some/other/path/query.rq`, what should the behavior be?

Is there any utility to allow to (optionally) specify a name for the endpoint possibly by adding a new `name` decorator or extending the YAML specification?

```yaml
title: Title of my API
description: Description of my API
contact:
  name: Contact Name
  url: https://www.mywebsite.org
licence: http://example.org/licence.html
queries:
  - name: foo
    url: https://www.mywebsite.org/query1.rq
  - name: bar
    url: https://www.mywebsite.org/query2.rq
  - name: baz
    url: https://www.otherwebsite.org/query3.rq
```
